version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/

hooks:
  BeforeInstall:
    - location: stop_container.sh
      timeout: 300
      runas: ec2-user

  AfterInstall:
    - location: start_container.sh
      timeout: 300
      runas: ec2-user